
name: Using Envs
on: [push]
env: 
  WF_ENV: Available to all jobs 

jobs:
  log-set-envs-and-default-envs: 
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env jobs
    steps:
      - name: Echo Variables 
        env: 
          STEP_ENV: Available to only this step 
        run: |
          # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          # echo "GITHUB_REF: ${GITHUB_REF}"
          echo "RUNNER_OS: ${RUNNER_OS} "
          # set by us
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
