# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
name: Events that triggers workflow
on:
  push:
    branches:
      - master
      - "feature/**" # matches featur/A, feature/B, doesn't match feature/A/A
      - "!feature/C" # excludes 
    tags: 
      - v1.*
    # based on what file paths are changed
    paths: 
      - "**.yml"
      - "!.yaml"
    # paths-ignore:
    # - 'docs/**'
  workflow_dispatch:
  # schedule:
  #   - cron: "0/5 * * * *"
  # pull_request:
  #   types: [closed, assigned, opened, reopened]

jobs: 
  say-hello: 
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello 
        run: |
          echo "Hello World"
