name: Using Actions 
on: push
jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: List Files 
        run: |
          pwd
          ls -a
      # https://github.com/marketplace/actions/checkout    
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      # https://github.com/actions/hello-world-javascript-action
      - name: Simple JS Action 
        uses: actions/hello-world-javascript-action@v1
        # A map of the input parameters defined by the action
        with: 
          who-to-greet: John