name: Approaval
on: [push, workflow_dispatch]

jobs:
  dev_approval:
    environment: dev_approve
    runs-on: ubuntu-latest
     steps:
      - run: echo "Approval from Developers has been given"

  run_command:
    #environment: dev_approve
    needs: 
      - dev_approval
    runs-on: ubuntu-latest
    steps:
      - run: echo "I received an approaval to run!"