name: Approaval
on: workflow_dispatch

jobs:
  run_command_after_approve:
    environment: dev_approve
    runs-on: ubuntu-latest
    steps:
      - run: echo "I received an approaval to run!"

  dev_approval:
    environment: dev_approve
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval from Developers has been given"
  command_01:
    needs: 
      - dev_approval
    runs-on: ubuntu-latest
    steps:
      - run: echo "I received an approaval to run!"
  command_02:
    needs: 
      - dev_approval
    runs-on: ubuntu-latest
    steps:
      - run: echo "I received an approaval to run, too!"